Update Padavan_toolchain.yml

diff --git a/.github/workflows/Padavan_toolchain.yml b/.github/workflows/Padavan_toolchain.yml
--- a/.github/workflows/Padavan_toolchain.yml
+++ b/.github/workflows/Padavan_toolchain.yml
@@ -1,5 +1,6 @@
-#修改TNAME: git
-name: Build Padavan_toolchain
+# by: TurBoTse
+
+name: Padavan toolchain
 
 on: 
   release:
@@ -7,60 +8,51 @@ on:
   push:
     tags:
     - 'v*'
-  #  branches: 
+#   branches: 
     - zerotier
 #  schedule:
 #    - cron: 0 8 * * 5
+  workflow_dispatch:
   watch:
     types: [started]
-
+env:
+  src_dir: /opt/rt-n56u
+  build_dir: /opt/rt-n56u/toolchain-mipsel
+  toolchain_dir: /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x
+  src_git: https://github.com/896660689/rt-n56u.git
 jobs:
   build:
-    runs-on: ubuntu-20.04
+    name: Build Padavan toolchain
+    runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
-
     steps:
-    - name: Checkout
-      uses: actions/checkout@master
-    - name: Initialization environment
-      env:
-        DEBIAN_FRONTEND: noninteractive
-      run: |
-        sudo apt-get update
-        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
-        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
-        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev gcc-multilib
-    - name: Clone source code
-      env:
-        TNAME: https://github.com/896660689/rt-n56u.git
-      run: |
-        git clone --depth=1 --branch=ad $TNAME /opt/rt-n56u
-    - name: Build Firmware
-      run: |
-        cd /opt/rt-n56u/toolchain-mipsel
-        if [ ! -f build_toolchain ] ; then
-        echo "build_toolchain not found "
-        exit 1
-        fi
-        ./clean_toolchain
-        ./build_toolchain
-        #
-    - name: tar_toolchain-mipsel
-      run: |
-        cd /opt/rt-n56u/toolchain-mipsel
-        tar zcvf toolchain-3.4.x.tar.gz toolchain-3.4.x
-        #
-        cd /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x
-        tar zcvf mipsel-linux-uclibc.tar.gz mipsel-linux-uclibc
-        #
-    - name : Upload toolchain-3.4.x.tar.gz
-      uses: actions/upload-artifact@master
-      with:
-        name: toolchain-3.4.x.tar.gz
-        path: /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x.tar.gz
-        #
-    - name : Upload mipsel-linux-uclibc.tar.gz
-      uses: actions/upload-artifact@master
-      with:
-        name: mipsel-linux-uclibc.tar.gz
-        path: /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/mipsel-linux-uclibc.tar.gz
+      - name: Prepare environment
+        run: |
+          sudo apt-get update
+          sudo apt-get upgrade
+          sudo apt-get install libtool-bin gperf python3-docutils autopoint gettext help2man
+      - name: Clone source code
+        run: |
+          git clone -b zerotier --depth=1 $src_git $src_dir
+      - name: Build toolchain
+        run: |
+          cd $build_dir
+          if [ ! -f build_toolchain ] ; then echo "build_toolchain.sh not found "; exit 1; fi
+          ./clean_toolchain
+          ./build_toolchain
+      - name: Compressed toolchain
+        run: |
+          cd $toolchain_dir
+          tar -caf mipsel-linux-uclibc.tar.xz *
+          cd $build_dir
+          tar -caf padavan_toolchain.tar.xz *
+      - name : Upload toolchain to Artifact
+        uses: actions/upload-artifact@main
+        with:
+          name: mipsel-linux-uclibc.tar.xz
+          path: ${{ env.toolchain_dir }}/mipsel-linux-uclibc.tar.xz
+      - name : Upload padavan toolchain
+        uses: actions/upload-artifact@main
+        with:
+          name: Padavan-toolchain.tar.xz
+          path: ${{ env.build_dir }}/padavan_toolchain.tar.xz
